### ISSUE TITLE
Misaligned buttons in 3.1.2

### ISSUE THREAD

**Issue by Stooovie** [jtbgroup/kodi-search-card#13]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Buttons are misaligned (to the left) in version 3.1.2 - the buttons should span the entire width. 

Was fine before. 

![0B800ECC-E07F-4772-A755-B39825E5C5DC](https://user-images.githubusercontent.com/10572373/170941025-0feb05a1-045e-4070-873c-42363906fdf6.jpeg)

### What version of a card has described problem?

3.1.2

### What was the last working version card?

3.1.1

### What browser (browsers/apps) does have this problem?

all

### What version of Home Assistant do you use?

2022.5.5

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:kodi-search-card
entity: sensor.kodi_media_sensor_search
show_thumbnail: true
title: Kodi
show_action_mode: false
action_mode: play
order:
  - episode
  - movie
```
