### ISSUE TITLE
No artists being displayed?

### ISSUE THREAD

**Issue by Rudd-O** [jtbgroup/kodi-search-card#15]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

I search for an artist that I know Kodi has (Chorus works and shows it), but the card shows it not.

Details here: https://github.com/jtbgroup/kodi-media-sensors/issues/19

### What version of a card has described problem?

latest

### What was the last working version card?

did not try old versions

### What browser (browsers/apps) does have this problem?

Firefox

### What version of Home Assistant do you use?

2022-08-01

### What type of installation are you running?

Home Assistant Core

### Card's configuration

```yaml
type: custom:kodi-search-card
entity: sensor.kodi_media_sensor_search
title: Search media
show_thumbnail: true
show_thumbnail_border: true
show_thumbnail_overlay: true
album_details_sort: date_desc
show_action_mode: true
action_mode: add
outline_color: rgb(74,200,50)
add_position: 3
media_type_order:
  - movie
  - album
  - song
  - episode
```

### Javascript errors shown in the browser's console (if applicable)

```shell
None.
```
