### ISSUE TITLE
custom element doesn't exist  : kodi-search-card in Android app

### ISSUE THREAD

**Issue by Turbomortel** [jtbgroup/kodi-search-card#18]
### Checklist

- [X] I have updated the card to the latest version available
- [X] I have cleared the cache of my browser
- [X] I have checked if the problem is already reported

### The problem

Hi there,

I'm very new with custom card so not sure if it's normal or not. The custom element doesn't work within the android application "custom element doesn't exist  : kodi-search-card",  while working perfectly in browsers.
Other custom card "like Lovelace Horizon Card" works without issue.

Thank you !

### What version of a card has described problem?

3.7.1

### What browser (browsers/apps) does have this problem?

the Android app

### What version of Home Assistant do you use?

2024.10.4

### What type of installation are you running?

Home Assistant OS

### Card's configuration

```yaml
type: custom:kodi-search-card
entity: sensor.kms_s_01jbs299fxen0hv0nawcsjhtgy
show_thumbnail: true
show_thumbnail_border: false
show_thumbnail_overlay: true
outline_color: var(--primary-text-color)
album_details_sort: date_desc
show_action_mode: true
show_recently_added: true
show_recently_played: true
action_mode: play
add_position: 1
order:
  - song
  - album
  - artist
  - movie
  - musicvideo
  - tvshow
  - episode
  - channel
  - filemusicplaylist
```
